language: java

dist: trusty

addons:
    sonarcloud:
        organization: "farao-community"
        token: ${SONAR_TOKEN}

script:
- git fetch --unshallow --quiet
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
- mvn clean verify sonar:sonar
