language: java

dist: trusty

git:
    depth: false

addons:
    sonarcloud:
        organization: "farao-community"
        token: ${SONAR_TOKEN}

script:
- git fetch origin master
- mvn clean verify sonar:sonar
