hades2:
    homeDir: $HOME/farao-dep/runtime/hades2
    timeout: -1
    debug: false

load-flow:
    default-impl-name: Hades2

load-flow-default-parameters:
    voltageInitMode: DC_VALUES
    transformerVoltageControlOn: false
    dcMode: false
    balanceType: PROPORTIONAL_TO_GENERATION_P

hades2-default-parameters:
    countriesToBalance: AL,AT,BA,BE,BG,CH,CZ,DE,ES,FR,GR,HR,HU,IT,ME,MK,NL,PL,PT,RO,RS,SI,SK,TR,UA

sensitivity-analysis:
    default-impl-name: Sensi2

hades2-default-sensitivity-parameters:
    computeInitialLoadflow: true
    computeSensitivityToPsts: true
    computeSensitivityToInjections: false
    equationTypePst: ANGLE_SHIFT_EQ
    resultsThreshold: -1
    hubPtdf: -1

rao:
    default: SearchTreeRao

rao-parameters:
    objective-function: MAX_MIN_MARGIN_IN_MEGAWATT
    max-number-of-iterations: 5
    pst-penalty-cost: 0.01
    pst-sensitivity-threshold : 0.0
    sensitivity-fallback-overcost: 0
    rao-with-loop-flow-limitation: false
    loop-flow-approximation: FIXED_PTDF
    loop-flow-constraint-adjustment-coefficient: 0.0
    loop-flow-violation-cost: 0.0
    mnec-acceptable-margin-diminution: 50.0
    mnec-violation-cost: 10.0
    mnec-constraint-adjustment-coefficient: 0.0

search-tree-rao-parameters:
    stop-criterion: POSITIVE_MARGIN
    maximum-search-depth: 5
    relative-network-action-minimum-impact-threshold: 0
    absolute-network-action-minimum-impact-threshold: 0
    leaves-in-parallel: 2

linear-rao-parameters:
    security-analysis-without-rao: false
