name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download and install OR-Tools
        shell: bash
        run: |
          wget -P /tmp https://github.com/google/or-tools/releases/download/v6.10/or-tools_flatzinc_ubuntu-18.04_v6.10.6025.tar.gz
          mkdir -p $HOME/farao-dep/runtime/or-tools
          tar -xzf /tmp/or-tools_flatzinc_ubuntu-18.04_v6.10.6025.tar.gz -C $HOME/farao-dep/runtime/or-tools --strip-components 1
          rm -f /tmp/or-tools_flatzinc_ubuntu-18.04_v6.10.6025.tar.gz
          echo '# OR-Tools config' >> $HOME/.bashrc
          echo 'export OR_TOOLS_HOME=$HOME/farao-dep/runtime/or-tools' >> $HOME/.bashrc
          echo 'export PATH=$PATH:$OR_TOOLS_HOME/bin' >> $HOME/.bashrc
          echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OR_TOOLS_HOME/lib' >> $HOME/.bashrc

      - name: Test env
        shell: bash
        run: env

      - name: Build with Maven
        run: mvn --batch-mode -Pcoverage install

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=farao-community
          -Dsonar.projectKey=com.farao-community.farao:farao-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
